/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alexsoto' at '1/12/16 4:49 PM' with Gradle 2.10
 *
 * @author alexsoto, @date 1/12/16 4:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
